version: '3'

networks:
    devopsApi:

services:
    postgresql:
        image: postgres:15.1
        ports:
            - 5455:5432
        env_file:
            - '../.env'
        environment:
            POSTGRES_DB: devopsApiDb
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        networks:
            - devopsApi
        volumes:
            - ./volumes/postgresql:/var/lib/postgresql/data
    pgadmin4:
        image: dpage/pgadmin4:latest
        env_file:
            - '../.env'
        ports:
            - 3500:80
        environment:
            - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}'
            - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}'
        volumes:
            - ./pgadmin/servers.json:/pgadmin4/servers.json
        networks:
            - devopsApi
